### ISSUE TITLE
Feature request - Add support for converting Poetry scripts

### ISSUE THREAD

**Issue by avi-cenna** [nahco314/poetry2rye#3]
Please add support for converting the Poetry scripts syntax to Rye syntax.

The poetry syntax looks like this:

```toml
[tool.poetry.scripts]
my-script = "my_package_name:log_revision.py"
```

If you think this is a reasonable addition, I can probably submit a PR for this.
